# Week 2 - Mini Assessment

Welcome to you mini assessment for week two. For this assessment, you will be completing 15 exercises where for each new exercise, the difficulty level will only increase. You've got this! 😎

At the end of an hour, we will walk over each question together. Feel free to post it on GitHub once you finish, under your respective folder for everything related to week 2.

1. import the numpy package and check its version.

In [4]:
import numpy as np

In [5]:
np.__version__

'1.18.4'

2. Create an numpy range of values from 0 to 49 and name it `mynums`.

In [9]:
np.arange (50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
mynums = np.arange (50)

3. Reshape the array you created in step 2 into a matrix with the shape below and assign a copy of it to a variable called `my_matrix`.

In [121]:
my_matrix = mynums.reshape (5,10)

In [122]:
my_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

4. Create a linearly-spaced array of size 100 between the numbers 20 to 100, assign it to the variable, `num_increases` and print it.

In [89]:
num_increases = np.linspace(20,100,100)

In [91]:
print(num_increases)

[ 20.          20.80808081  21.61616162  22.42424242  23.23232323
  24.04040404  24.84848485  25.65656566  26.46464646  27.27272727
  28.08080808  28.88888889  29.6969697   30.50505051  31.31313131
  32.12121212  32.92929293  33.73737374  34.54545455  35.35353535
  36.16161616  36.96969697  37.77777778  38.58585859  39.39393939
  40.2020202   41.01010101  41.81818182  42.62626263  43.43434343
  44.24242424  45.05050505  45.85858586  46.66666667  47.47474747
  48.28282828  49.09090909  49.8989899   50.70707071  51.51515152
  52.32323232  53.13131313  53.93939394  54.74747475  55.55555556
  56.36363636  57.17171717  57.97979798  58.78787879  59.5959596
  60.4040404   61.21212121  62.02020202  62.82828283  63.63636364
  64.44444444  65.25252525  66.06060606  66.86868687  67.67676768
  68.48484848  69.29292929  70.1010101   70.90909091  71.71717172
  72.52525253  73.33333333  74.14141414  74.94949495  75.75757576
  76.56565657  77.37373737  78.18181818  78.98989899  79.7979798
  80.6060606

5. Create an numpy array with 20 zeros, assign it to the variable `zeroes`.

In [14]:
zeroes = np.full (20,0)

In [17]:
zeroes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

6. Create a two dimensional array of size 7 by 8 filled with 1s and do the following:
- mulptiply the first row by 2
- add 3 and raise to the power of two the odd columns starting from the beginning
- subtract 10 and multiply by 15 the elements in the even rows and odd columns

In [79]:
array = np.full (7*8,1)

In [234]:
array1 = array.reshape (7,8).copy()

In [235]:
array1

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [82]:
array1[0] = (array1[0]*2) #mulptiply the first row by 2

In [83]:
array1

array([[2, 2, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [84]:
array1[:, ::2] = ((array1[:, ::2]+3)**2) #- add 3 and raise to the power of two the odd columns starting from the beginning


In [85]:
array1

array([[25,  2, 25,  2, 25,  2, 25,  2],
       [16,  1, 16,  1, 16,  1, 16,  1],
       [16,  1, 16,  1, 16,  1, 16,  1],
       [16,  1, 16,  1, 16,  1, 16,  1],
       [16,  1, 16,  1, 16,  1, 16,  1],
       [16,  1, 16,  1, 16,  1, 16,  1],
       [16,  1, 16,  1, 16,  1, 16,  1]])

In [86]:
array1[1::2, ::2] = ((array1[1::2, ::2]-10)*15) #- subtract 10 and multiply by 15 the elements in the even rows and odd columns

In [87]:
array1

array([[25,  2, 25,  2, 25,  2, 25,  2],
       [90,  1, 90,  1, 90,  1, 90,  1],
       [16,  1, 16,  1, 16,  1, 16,  1],
       [90,  1, 90,  1, 90,  1, 90,  1],
       [16,  1, 16,  1, 16,  1, 16,  1],
       [90,  1, 90,  1, 90,  1, 90,  1],
       [16,  1, 16,  1, 16,  1, 16,  1]])

7. Create a numpy array starting with 20 and ending with 40 with 10 equally spaced values.

In [92]:
new_array1 = np.linspace(20,40,10)

In [94]:
len(new_array1)

10

In [95]:
print(new_array1)

[20.         22.22222222 24.44444444 26.66666667 28.88888889 31.11111111
 33.33333333 35.55555556 37.77777778 40.        ]


8. Create a 9 by 9 matrix with random integers from 100 to 500 and use the dtype "int32".

In [105]:
matrix = np.random.randint(100,500,(9,9), dtype='int32')

In [107]:
print(matrix.dtype)

int32


In [131]:
matrix

array([[149, 160, 198, 361, 279, 289, 155, 286, 373],
       [137, 273, 314, 241, 135, 252, 375, 429, 207],
       [103, 355, 197, 447, 330, 335, 291, 162, 391],
       [443, 375, 396, 230, 242, 118, 461, 255, 169],
       [297, 256, 160, 359, 465, 116, 222, 432, 382],
       [374, 184, 120, 173, 352, 141, 257, 107, 247],
       [260, 470, 166, 444, 318, 446, 274, 343, 103],
       [302, 107, 245, 276, 489, 243, 374, 345, 325],
       [282, 142, 318, 298, 302, 214, 397, 195, 429]])

9. Create an empty array of 20 elements with shape 2 by 10, dtype 'float32' and add a different number to each row.

In [132]:
empty_array = np.empty((2,10),'float32')

In [133]:
empty_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

10. Create an array with 15 random numbers between 100 and 200 and print the maximum value in the array.

In [127]:
matrix1 = np.random.randint(100,200,15)

In [128]:
matrix1

array([127, 100, 127, 146, 190, 144, 128, 189, 142, 152, 188, 126, 101,
       177, 125])

11. Create an array with the following numbers [40, 41, 26, 14, 15, 47, 43, 33, 44, 22], select the 5th to 10th elements, assign each to a new variable, change their value, and then print all 3 (the first array and your next two variables.

In [230]:
array2 = [40, 41, 26, 14, 15, 47, 43, 33, 44, 22]
array2

[40, 41, 26, 14, 15, 47, 43, 33, 44, 22]

In [227]:
fith_element = array2[4]
fith_element

15

In [228]:
tenth_element = array2[9]
tenth_element

22

In [232]:
array2[4] = 5
array2[9] = 10

In [233]:
print (array2, fith_element, tenth_element)

[40, 41, 26, 14, 5, 47, 43, 33, 44, 10] 15 22


12. Create an array of 360 random numbers from -10 to 50 (to resemble the weather) and find the min, max, 25th percentile, 75 percentile, and the median.

In [149]:
array4 = np.random.randint(-10,50,360)
array4

array([ 19,   0,  46,   8,  36,   2, -10,  33,   5,  46,  26,  29,  18,
        -6,  20,  30,  34,  44,   7,  -8,  10,  -1,  23,  -1,  -9,  33,
        36,  10,   8,  -6,  11,  23,  17,  -7,  25,  45,  39,  39,  28,
        -6,  -3,  49,   2,  36, -10,  20,  40,  13,  35,  37,  45,  13,
        41,  14,   1,  40,  40,  38,  28,  49,  17,   3,  33,  16,  39,
        38,  39,   8,  38,   7,  -9,  46,   1,  26,  18,  17,  34,   7,
        28,  43,  24,  12,  30,  13,  48,   0,  20,  45,  -9,   4,  44,
        31,  23,  18,  33,  18,  45,   1,  12,  34,  13,  10,  12,   1,
        29,  -1,  -9,  14,  32,  -3,   7,  43,  41,  43,   8,  18,  18,
        -7,  20,   0,  13, -10,  37,   7,   3,   9, -10,  32,  -9,  10,
        39,  26,   7,  14,  23,  41,  48,  40,  42,   6,  38,   6,  14,
        31,  28,  45,  -1,  32,  21,  27,  44,  29,  40,   7,  -9,  18,
         3,  11,  11,  -9,   9,   1,  42,  34,   5,  14,  46,  -2,  -4,
        40,   4,   2,  -8,   4,  39,  -7,  42, -10,  33,  27,  1

In [151]:
np.min(array4)

-10

In [152]:
np.max(array4)

49

In [154]:
np.percentile(array4,25)

5.75

In [156]:
np.percentile(array4,75)

34.0

In [157]:
np.median(array4)

18.0

13. Reshape the array you created in step 12 into a matrix of 300 by 12 ad get the same values but only for the months this time.

In [174]:
array_months = array4.reshape(12,30).copy() #assuming 30 days, not 300
array_months

array([[ 19,   0,  46,   8,  36,   2, -10,  33,   5,  46,  26,  29,  18,
         -6,  20,  30,  34,  44,   7,  -8,  10,  -1,  23,  -1,  -9,  33,
         36,  10,   8,  -6],
       [ 11,  23,  17,  -7,  25,  45,  39,  39,  28,  -6,  -3,  49,   2,
         36, -10,  20,  40,  13,  35,  37,  45,  13,  41,  14,   1,  40,
         40,  38,  28,  49],
       [ 17,   3,  33,  16,  39,  38,  39,   8,  38,   7,  -9,  46,   1,
         26,  18,  17,  34,   7,  28,  43,  24,  12,  30,  13,  48,   0,
         20,  45,  -9,   4],
       [ 44,  31,  23,  18,  33,  18,  45,   1,  12,  34,  13,  10,  12,
          1,  29,  -1,  -9,  14,  32,  -3,   7,  43,  41,  43,   8,  18,
         18,  -7,  20,   0],
       [ 13, -10,  37,   7,   3,   9, -10,  32,  -9,  10,  39,  26,   7,
         14,  23,  41,  48,  40,  42,   6,  38,   6,  14,  31,  28,  45,
         -1,  32,  21,  27],
       [ 44,  29,  40,   7,  -9,  18,   3,  11,  11,  -9,   9,   1,  42,
         34,   5,  14,  46,  -2,  -4,  40,   4,   2,

In [180]:
def min_Max_Median_Percentiles():
    for i in array_months:
        min_temp = np.min(i)
        max_temp = np.max(i)
        median_temp = np.median(i)
        twenty_five = np.percentile(i,25)
        seventy_five = np.percentile(i,75)
        print (i)  
        print(f'The minimum, maximum and median temperature for each month is:\n{min_temp}C , {max_temp}C , {median_temp}C')
        print(f'The 25th percentile and 75th percentile temperature ranges are:\n {twenty_five}C , {seventy_five}C')
        print()
min_Max_Median_Percentiles()

[ 19   0  46   8  36   2 -10  33   5  46  26  29  18  -6  20  30  34  44
   7  -8  10  -1  23  -1  -9  33  36  10   8  -6]
The minimum, maximum and median temperature for each month is:
-10C , 46C , 14.0C
The 25th percentile and 75th percentile temperature ranges are:
 0.5C , 32.25C

[ 11  23  17  -7  25  45  39  39  28  -6  -3  49   2  36 -10  20  40  13
  35  37  45  13  41  14   1  40  40  38  28  49]
The minimum, maximum and median temperature for each month is:
-10C , 49C , 28.0C
The 25th percentile and 75th percentile temperature ranges are:
 13.0C , 39.75C

[17  3 33 16 39 38 39  8 38  7 -9 46  1 26 18 17 34  7 28 43 24 12 30 13
 48  0 20 45 -9  4]
The minimum, maximum and median temperature for each month is:
-9C , 48C , 19.0C
The 25th percentile and 75th percentile temperature ranges are:
 7.25C , 37.0C

[44 31 23 18 33 18 45  1 12 34 13 10 12  1 29 -1 -9 14 32 -3  7 43 41 43
  8 18 18 -7 20  0]
The minimum, maximum and median temperature for each month is:
-9C , 45C , 18.0C
T

14. Create a mask for your data, and filter out and print:
- average temperature of the days where the temperature was below 10
- average temperature of the days where the temperature was greater than 30

In [185]:
below_ten = array4 < 10
warmer_thirty = array4 > 30

In [210]:
cold_days = np.mean(array4[below_ten])
hot_days = np.mean(array4[warmer_thirty])

In [211]:
print(f"The Average temperature on cold days was {cold_days:.2f}C ☀️")
print(f"The Average temperature on hot days was {hot_days:.2f}C 😎")

The Average temperature on cold days was 0.54C ☀️
The Average temperature on hot days was 39.98C 😎


15. Create a full 10 by 10 matrix with a number of your choosing and assign it to a variable. After printing that variables, unravel the matrix and assign the array to a new number.

In [215]:
all_ones = np.full((10,10),1)
all_ones

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [224]:
two = all_ones.ravel() + 1
two

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])